Fix being able to dupe items via Machine Access Interface
GregTechCEu/GregTech pull request #1021
Opened 2022-06-08 07:14 UTC by ALongStringOfNumbers

**What:**
Fixes being able to dupe machines with the Machine Access Interface as shown in #1008 

**Implementation Details:**
The dupe was occurring because of the `super.insertItems` call in the `MetatileEntityMachineHatch` item handler returning the stack when attempting to insert into a slot that had reached/exceeded its slot limit.

This fix simply sets the base slot limit of the Machine Access Interface to 16 (The amount for a regular Processing Array). The fix was done this way to also prevent people from attempting to cheese things, by placing a stack of machines into a Machine Access Interface attached to an unformed PA, and then forming the PA, thus having 1 stack of machines when the PA is only supposed to handle 16.

This works around the problematic behavior when the amount in the slot was greater than the slot limit.

**Outcome:**
Fixes being able to dupe machines in the Machine Access Interface. Closes #1008

2022-06-08 10:58 UTC, Exaxxion commented
Seems prudent enough, though I do have one concern: have you tried forming an advanced PA, then without breaking the machine hatch, forming a basic PA with that hatch and trying the dupe exploit again?

2022-06-08 15:19 UTC, Quarri6343 reviewed
I tested it in game and found it does not fix anything
you still can reproduce #1008  with following steps:
1. form Advanced PA
2. put 64 machines into Machine Access Interface
3. unform Advanced PA
4. open Interface UI and shift click the machine in your inventory

2022-07-20 17:39 UTC, ALongStringOfNumbers commented
@Quarri6343 Could you try this again? I believe I have gotten it working correctly, at least I could not reproduce the issue when I tried.

2022-07-26 00:37 UTC, ModdedEngineer commented
If this keeps happening, I do have one idea. A advanced machine access interface could be added, which must be used for the advanced PA, and cannot be used for the normal PA. Since the stack of machines had to be allowed in the machine access interface because of the advanced PA, this should make it so that the machine access interface would not need to allow more than 16 machines.

2022-08-10 04:00 UTC, TechLord22 requested changes

2022-08-10 04:04 UTC, ALongStringOfNumbers commented on src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMachineHatch.java
> +            if(!ItemStackHashStrategy.comparingAllButCount().equals(stack, this.getStackInSlot(slot)) && !this.getStackInSlot(slot).isEmpty()) {
This is already done in a separate check on previous lines

2022-08-14 02:13 UTC, TechLord22 approved these changes

2022-08-18 19:14 UTC, merged