extend ShapedOreRecipe along with implementing a fluid ingredient for crafting recipes
GregTechCEu/GregTech pull request #1127
Opened 2022-08-11 05:03 UTC by PrototypeTrousers

## What
Allows crafting recipes to actually CHECK for the actual fluid in a bucket. since Forge doesnt account for any of it by itself.

## Implementation Details
Properly implementing container item methods allows for use of drums and quantum tanks to be used along with those recipes, without being consumed

## Outcome
Fixes: #1125

## Potential Compatibility Issues
None *wishful thinking*

2022-08-12 01:27 UTC, ALongStringOfNumbers commented on src/main/java/gregtech/api/recipes/ModHandler.java
> +        IRecipe shapedOreRecipe = new GTShapedOreRecipe(null, result.copy(), finalizeShapedRecipeInput(recipe))
This should also be applied in `MirroredShaped`

2022-08-14 02:03 UTC, ALongStringOfNumbers commented on src/main/java/gregtech/common/crafting/GTFluidCraftingIngredient.java
> +            if (fluidStack == null || fluidStack.amount == 0) return true;
Should this return false?

2022-08-14 02:09 UTC, ALongStringOfNumbers commented on src/main/java/gregtech/api/items/metaitem/stats/ItemFluidContainer.java
> +            if (drained.amount == 1000) {
You have added this to cells that can contain greater than 1000 mb of fluid, as well as contain variable amounts of fluid, maybe being less than 1000 mb. Should this instead check if `drained.amount > 0`? and should drained be changed to `handler.drain(Integer.MAX_VALUE, false)`?

2022-08-16 04:51 UTC, TechLord22 requested changes

2022-08-16 04:51 UTC, TechLord22 commented on src/main/java/gregtech/api/block/machines/MachineItemBlock.java
> +            if (itemStack.getCapability(CapabilityFluidHandler.FLUID_HANDLER_ITEM_CAPABILITY, null) != null) {
This if statement should be removed.

2022-08-16 04:51 UTC, TechLord22 commented on src/main/java/gregtech/api/block/machines/MachineItemBlock.java
> +        return itemStack.getCapability(CapabilityFluidHandler.FLUID_HANDLER_ITEM_CAPABILITY, null).getContainer().copy();
Does this have a risk of a NullPointerException?

2022-08-16 04:51 UTC, TechLord22 commented on src/main/java/gregtech/common/crafting/GTFluidCraftingIngredient.java
> +        this.fluidStack = stacks[0].getCapability(CapabilityFluidHandler.FLUID_HANDLER_ITEM_CAPABILITY, null).drain(Integer.MAX_VALUE, false);
Should we throw an IllegalArgumentException here when the first ItemStack does not have the capability?

2022-08-16 04:51 UTC, TechLord22 commented on src/main/java/gregtech/common/crafting/GTShapelessOreRecipe.java
> +        {
This class needs the EditorConfig formatting applied.

2022-08-18 01:12 UTC, TechLord22 approved these changes

2022-08-18 01:15 UTC, merged