Only show ores whose stone types should be dropped on Prospector map
GregTechCEu/GregTech pull request #1207
Opened 2022-09-22 03:40 UTC by ALongStringOfNumbers

## What
Since Brachy's change that correctly fetched the meta for blocks from a blockstate, the ore prospector maps show all stone types of ore in the ore list on the right.

It is sort of spammy and drastically lengthens the list to show all stone types for all the ores found in the scanning range of the prospector, therefore this PR makes it so that only stone types that can be dropped are shown in the list, and anything that cannot be dropped is converted into the default (Stone) StoneType of the ore block.

An image of the prospector on current `master`:
![2022-09-21_20 28 26](https://user-images.githubusercontent.com/31759736/191653196-6beaf61b-9512-4de7-9d3a-5f4d477aa40c.png)

An image of the prospector in this PR:
![2022-09-21_20 25 19](https://user-images.githubusercontent.com/31759736/191653243-e1bb56a2-a907-4fb4-ad70-3b46d00aaf6e.png)

## Outcome
Only show ores that can be dropped on the ore list in prospectors, and convert everything else into the default stone type.

2022-09-26 13:27 UTC, Zalgo239 approved these changes

2022-09-26 14:48 UTC, brachy84 requested changes

2022-09-26 14:48 UTC, brachy84 commented on src/main/java/gregtech/common/terminal/app/prospector/widget/WidgetProspectingMap.java
> +                                        OrePrefix prefix = OreDictUnifier.getPrefix(itemBlock);
this can be put outside the loop

2022-09-26 14:48 UTC, brachy84 commented on src/main/java/gregtech/common/terminal/app/prospector/widget/WidgetProspectingMap.java
> +                                            added = true;
missing `break;`?

2022-09-26 14:48 UTC, brachy84 commented on src/main/java/gregtech/common/terminal/app/prospector/widget/WidgetProspectingMap.java
> +                                                added = true;
missing `break;`?

2022-09-28 04:50 UTC, brachy84 approved these changes

2022-09-29 15:28 UTC, merged