allow addons to control which recipes are registered
GregTechCEu/GregTech pull request #1257
Opened 2022-10-31 04:50 UTC by TechLord22

## What
This PR allows addons to control which recipes GT or other addons register. Each major group of recipes now has an event fired for checking if it should be registered. Other mods can choose to stop GT from registering the recipes accordingly, and also implement this system for themselves, allowing other mods to cancel addons' recipes as well.

This is potentially useful for modpacks with core mods, which want to disable a lot of GT's default content without manually removing everything.

## Outcome
Allows addons to control which recipes are registered.

2022-11-01 20:14 UTC, LAGIdiot reviewed
I like idea behind this PR. This will be definitely makes integration with GTCEu easier.

Will we know is someone cancels our registration? Will it be logged somewhere on global level? Because if not it will be hard to know what broke and why are recipes missing.

Is it possible to load GTCEu without any recipes? Does it run? As I feel there maybe possible crashes because of incorrect null/empty checks. Also those it really stars empty or there are some hardcoded which this does not cover?

2022-11-01 20:14 UTC, LAGIdiot commented on src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
>      public static void init() {
Registration is quite inconsistent and hard to follow. Like where whole init function should be registered and where just part of the file.

2022-11-01 20:14 UTC, LAGIdiot commented on src/main/java/gregtech/loaders/recipe/GTRecipeLoaders.java
> +public enum GTRecipeLoaders implements IRecipeLoader {
I feel this either needs to be grouped by virtual categories or in alphabetic order. As right now for someone who is it not using everyday it is hard to find right category in all of these.

2022-11-07 07:20 UTC, LAGIdiot requested changes
As per my previous comments.

2022-11-17 17:34 UTC, LAGIdiot commented
There were some recipe changes (mostly moving them between files) in #1276 which may need to be reflected here

2023-06-14 03:58 UTC, serenibyss commented
Should be no longer needed with #1847

2023-06-14 03:58 UTC, closed without merging