Allow Taping crates to keep inventory
GregTechCEu/GregTech pull request #1310
Opened 2022-12-01 04:07 UTC by ALongStringOfNumbers

## What
Allows using tape on crates to allow the crate to keep its inventory.

Currently a couple minor issues that still need fixing, namely that the taped status is not being saved to the crate, so the crate contents are not being initialized when placed.

Also needs a new overlay for being taped. Basically just the maintenance taped overlay, but without the maintenance overlay in the background

## Outcome
Allow taping crates so that they keep their inventory when broken.

2022-12-04 06:48 UTC, LAGIdiot requested changes
It works, but I think it needs to be more polished before it will be usable. So for now, I will block it with list of things to address or at least discuss.

- [ ] Create from JEI doesn't stack with placed and broken one (NBT for taped is left in)
- [ ] taped Create in inventory looks exactly same as un-taped one
- [ ] there is no indication either on crate that it is movable when taped
- [ ] or on tape that it can be used for taping Creates to make them movable
- [ ] already taped Crate can be taped again (consumes tape again)
- [ ] colored (sprayed with Spray can) taped Crate losses color when broken - this could be really confusing as player may have colored them specifically so that he knows what is inside
- [ ] tape is possible to make only from HV+
- [ ] taped Crates are stackable (if they have same content, would be better to make them unstackable so there is no need for nbt comparison)
- [ ] taped is not reset when Create is placed again which means it can be picked again (without spilling content)
- [ ] graphical glitch showing tapped overlay on placed Crate for split second

2023-04-05 17:43 UTC, ALongStringOfNumbers commented
The tape being only available from HV+ is something that I realized after making this PR. However, I do knot want to do any balance changes in this PR, just introduced the feature and leave any balancing to another PR, as it might touch more than just the tape.

I could not reproduce the graphical glitch that you mentioned at all

2023-04-06 00:09 UTC, LAGIdiot commented
> The tape being only available from HV+ is something that I realized after making this PR. However, I do not want to do any balance changes in this PR, just introduced the feature and leave any balancing to another PR, as it might touch more than just the tape.

I think this is wrong approach. As we may not get to it that soon which would mean that this feature is not so useful. It would be a different story, if there was some array of items which can be used to tap crates, and we registered only tape but anyone (mostly modpack devs) could register other items from get on.

2023-04-06 00:59 UTC, ghzdude commented
> The tape being only available from HV+ is something that I realized after making this PR. However, I do not want to do any balance changes in this PR, just introduced the feature and leave any balancing to another PR, as it might touch more than just the tape.

It's possible to make duct tape as early as LV? The earliest recipe (as of 2.5.4) just involves carbon and polyethylene, both of which are do-able in LV, unless there's something I'm missing.

2023-04-06 01:20 UTC, LAGIdiot commented
> > The tape being only available from HV+ is something that I realized after making this PR. However, I do not want to do any balance changes in this PR, just introduced the feature and leave any balancing to another PR, as it might touch more than just the tape.
> 
> It's possible to make duct tape as early as LV? The earliest recipe (as of 2.5.4) just involves carbon and polyethylene, both of which are do-able in LV, unless there's something I'm missing.

I may have missed the Polyethylene only chain, and I see now if you use cracking in Chemical reactor you can distill Ethylene in LV. In that case it is available early enough, but to find this chain is not easy. It would be way easier if there was some early type just for this, something from glue, paper and wood pulps, maybe?

2023-04-06 08:46 UTC, DStrand1 commented on src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCrate.java
>      private ItemStackHandler inventory;
Can this field be made `protected`? It's useful for addons (TJCore) that are trying to extend this class

2023-11-09 20:18 UTC, planetme commented
real

2023-11-15 05:10 UTC, serenibyss approved these changes

2023-11-15 05:13 UTC, merged