Add method for recycling recipes to use nbt conditions
GregTechCEu/GregTech pull request #1443
Opened 2023-01-24 05:29 UTC by ALongStringOfNumbers

## What
This PR adds a method for recycling recipes to provide nbt conditions based on the typr of input that is trying to be recycled. Currently this is used to ignore nbt from machines that have been renamed, which Closes #1442 

## Outcome
Add a method for recycling recipes to provide nbt conditions

2023-01-24 05:51 UTC, Caedis reviewed
Looks good from my end. Issue was resolved in my test world.

2023-02-08 05:46 UTC, TechLord22 requested changes

2023-02-08 05:46 UTC, TechLord22 commented on src/main/java/gregtech/loaders/recipe/RecyclingRecipes.java
> +            NBTCondition condition = NBTCondition.create(NBTTagType.STRING, GregtechDataCodes.CUSTOM_NAME, "");
This NBTCondition can be saved as a constant to reduce memory allocation/GC pressure during recipe registration. This method will be called a lot of times.

2023-03-18 02:59 UTC, TechLord22 approved these changes

2023-03-18 02:59 UTC, merged