Battery Buffer Tweaks
GregTechCEu/GregTech pull request #302
Opened 2021-12-06 22:51 UTC by TechLord22

Changes 9 Slot buffers to 8 slots. Evenly distributes energy over all batteries when draining and filling.

2021-12-08 16:16 UTC, brachy84 requested changes

2021-12-08 16:16 UTC, brachy84 commented on src/main/java/gregtech/api/capability/impl/EnergyContainerBatteryBuffer.java
> +            long amperageUsed = energyContainer.acceptEnergyFromNetwork(outFacing.getOpposite(), distributed / getOutputAmperage(), getOutputAmperage());
shouldn't this be `distributed * getOutputAmperage()`?
(described issue on discord)

2021-12-08 16:16 UTC, brachy84 commented on src/main/java/gregtech/api/capability/impl/EnergyContainerBatteryBuffer.java
>      private long lastEnergyInputPerSec = 0;
you need to update these 4 values for the digital cover

2021-12-12 09:32 UTC, DStrand1 commented
Superseded by #323

2021-12-12 09:32 UTC, closed without merging