In-world Multiblock Previews
GregTechCEu/GregTech pull request #407
Opened 2021-12-26 19:23 UTC by bruberu

Simply adds multiblock previewing, like with a freedom wrench in gregicality. Can be accessed by a shift-right-click.
The lighting may be slightly off, but it shouldn't be a big deal in most circumstances.
Currently, only one multiblock at a time may be rendered in this way, but this is done entirely client-side, so this shouldn't be a problem.

![image](https://user-images.githubusercontent.com/80226372/147418013-bd0516f1-8a10-4c8a-80f6-e65f2fc9a893.png)

2021-12-27 12:34 UTC, TechLord22 requested changes
In addition to my comment, the preview can never be removed, even when breaking the controller. It should be removed after the structure is successfully formed or if the controller is broken.

2021-12-27 12:34 UTC, TechLord22 commented on src/main/java/gregtech/api/metatileentity/multiblock/MultiblockControllerBase.java
> +        if (!this.isStructureFormed() && playerIn.isSneaking() && this.rightClickDelayTimer == 0 && this.getWorld().isRemote) {
This should check if the player's hand is empty. Otherwise, attempting to place blocks on top of the controller will cycle the preview.

2021-12-28 02:17 UTC, ALongStringOfNumbers commented
I did not see any issues when briefly testing, but this is not my forte

2021-12-28 06:52 UTC, DStrand1 approved these changes

2021-12-28 06:52 UTC, merged