Trim Factor and Fluid Trimming
GregTechCEu/GregTech pull request #409
Opened 2021-12-27 02:45 UTC by ALongStringOfNumbers

**What:**
Introduces a "Trim Factor" for how much recipes should be trimmed to. This is useful for EG macerators in the PA, where we want to trim to 1 for LV and MV macerators, to 3 for HV macerators, and not at all for EV+ macerators.

This trim factor is modified in a Pair<Boolean, Integer> where the boolean value controls if the trimming actually happens.

This PR also introduces Fluid output trimming, with support for chanced fluid outputs marked as TODO, as we don't have any recipes that take advantage of them yet. This will be useful in the upcoming generator PR by trimming outputs to 0 if there is no fluid output hatch in the structure.

This "Trim Factor" can function like a rudimentary voiding system, by simply trimming the number of outputs to 0. This is rudimentary logic because it does not depend on the state of the output bus/available room for outputs at all, but rather hard trimming all recipes to a certain number

2021-12-31 22:43 UTC, PrototypeTrousers commented on src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityProcessingArray.java
could these checks for macerators be made generic to something like this ?
            if (mte.getExportItems().getSlots() < mte.getRecipeMap().getMaxOutputs()) {
                return Pair.of(true, mte.getExportItems().getSlots());
            }

2021-12-31 23:11 UTC, PrototypeTrousers approved these changes

2022-01-02 03:31 UTC, Syrcan requested changes

2022-01-05 13:52 UTC, Syrcan commented
This seems to be getting to a point where the code becomes too overengineered.
We have two sorts of trimming logic:
- The old one, what the macerator uses and being based on the number of slots, which is calculated in `getResultItemOutputs(int maxOutputSlots, int tier)`
- And the new one, a giant piece of code, which does hacky things with streams after running the method just above

So... why not combine both? All you would need to do would be like this:
```java
int actualTrim = logicTrim == -1 ? outputSlots : Math.min(logicTrim, outputSlots);
this.itemOutputs = GTUtility.copyStackList(recipe.getResultItemOutputs(actualTrim, voltageTier));
```
That would still mean `getResultItemOutputs` needs a small rewrite, but nothing as big and complicated as what we have here.

2022-01-05 14:39 UTC, Syrcan commented
I'm wondering if we should take this a step further and enforce this new trimming logic over the number of slots checks everywhere (so, for the macerator).
EBF voiding the 2nd output with ULV output bus "because that's how the macerator works" is a really silly bug in my opinion.

2022-01-05 21:48 UTC, ALongStringOfNumbers commented
> I'm wondering if we should take this a step further and enforce this new trimming logic over the number of slots checks everywhere (so, for the macerator). EBF voiding the 2nd output with ULV output bus "because that's how the macerator works" is a really silly bug in my opinion.

Even if we replace the slot logic with the trimming logic, the same thing would happen for the EBF and other multis. There is 1 available slot, so the recipe would be trimmed down to 1 output. Even your proposed solution in the comment above will run into the issue.

2022-01-22 19:18 UTC, ALongStringOfNumbers commented
Superseded by #559

2022-01-22 19:18 UTC, closed without merging