Update OrePrefix.java
GregTechCEu/GregTech pull request #436
Opened 2021-12-30 15:30 UTC by Yefancy

i did meet this issue when i work with NC.
because the hidden orePrefix wont register the fluid. but the oredict added by other mod will also add its recipes.

2021-12-30 15:31 UTC, Rongmario approved these changes

2021-12-30 23:19 UTC, ALongStringOfNumbers commented
This does fix the Null Fluid crash, after testing with HBM (Although there are still issues with that mod because of invalid CEu recipes)

2021-12-30 23:19 UTC, ALongStringOfNumbers approved these changes

2021-12-30 23:22 UTC, TechLord22 requested changes

2021-12-30 23:22 UTC, TechLord22 commented on src/main/java/gregtech/api/unification/ore/OrePrefix.java
> +            if (material.isHidden() && material.hasFluid()) {
This also needs to check for a potential plasma. It only checks for non-plasma fluids right now, so a mod registering a plasma with the same name as CEu can still have problems. Additionally, materials can have plasmas without fluids.

2021-12-31 04:21 UTC, TechLord22 approved these changes

2021-12-31 04:21 UTC, merged