Chemistry fixes
GregTechCEu/GregTech pull request #624
Opened 2022-02-08 13:28 UTC by m2r1k5

**What:**
Closes #622, #623. 
Disables Nitrobenzene decomposition to prevent dupes
Fix Butene formula being wrong

2022-02-08 13:33 UTC, Syrcan commented
In general, we have our LCR recipes void some of the secondary outputs in recipes (typically Oxygen and Hydrogen) for the sake of conveniency and gameplay balance. These recipe fixes don't need to output either of those fluids. Otherwise it sounds like a good fix.

2022-02-08 13:36 UTC, pablocnvs commented
You could be a little more evil by quinduplicating the amount of H and remain consistent, but otherwise looks fine

2022-02-08 14:25 UTC, m2r1k5 commented
> In general, we have our LCR recipes void some of the secondary outputs in recipes (typically Oxygen and Hydrogen) for the sake of conveniency and gameplay balance. These recipe fixes don't need to output either of those fluids. Otherwise it sounds like a good fix.

To clarify, would you like me to get rid of the O and H secondary outputs?
Also, with voiding covers on the way, the convenience part won’t be as significant

2022-02-13 16:33 UTC, TechLord22 requested changes

2022-02-13 16:33 UTC, TechLord22 commented on src/main/java/gregtech/api/unification/material/materials/OrganicChemistryMaterials.java
> +                .components(Carbon, 3, Hydrogen, 5, Chlorine, 1)
The components of this compound should be kept, as we use it specifically for autogenerated decomposition. The tooltip however should be changed to `C3H5Cl`.

2022-02-14 19:55 UTC, ALongStringOfNumbers commented
Something went wrong with the commits in this PR

2022-02-21 18:49 UTC, TechLord22 approved these changes

2022-02-21 18:49 UTC, merged