Cleanups for minor IDE warnings
GregTechCEu/GregTech pull request #637
Opened 2022-02-11 05:51 UTC by ALongStringOfNumbers

**What:**

Cleans up some minor IDE warnings

2022-02-11 17:46 UTC, Rongmario requested changes

2022-02-11 17:46 UTC, Rongmario commented on src/main/java/gregtech/api/unification/material/properties/OreProperty.java
> +    @Nonnull
We tend to just use `@Nullable` and not `@Nonnull`, just remove this one.

2022-02-12 01:15 UTC, Rongmario approved these changes

2022-02-13 18:40 UTC, brachy84 approved these changes

2022-02-13 19:19 UTC, merged