Clipboard+
GregTechCEu/GregTech pull request #647
Opened 2022-02-13 17:56 UTC by brachy84

- reworked all clipboard textures to make it look more like a clipboard
- fix a issue where multiple textfields can be selected
- fix place behaviour. Before it was facing player look dir, now it is block face placed on
- when the neighbour changed and the block it is placed on becomes invalid the clipboard breakes

old
![grafik](https://user-images.githubusercontent.com/45517902/153768031-4677c923-ebfc-49d9-8dd9-d898d36d7481.png)

new
![grafik](https://user-images.githubusercontent.com/45517902/153768038-77162b55-d69a-479d-9b8c-8e0b0ff3e98a.png)

2022-02-15 10:08 UTC, Rongmario requested changes

2022-02-15 10:08 UTC, Rongmario commented on src/main/java/gregtech/common/metatileentities/MetaTileEntityClipboard.java
> +            this.scheduleRenderUpdate();
setBlockState with flag 3 should sync to client and ask for a render update, would `scheduleRenderUpdate` be needed?

2022-02-15 10:08 UTC, Rongmario commented on src/main/java/gregtech/common/metatileentities/MetaTileEntityClipboard.java
> +            Block.spawnAsEntity(getWorld(), this.getPos(), drops.get(0));
Use the `pos`?

2022-02-16 13:35 UTC, ChromaPIE commented
Had a little test with #645 also merged into my fork. The clipboard follows the UI color setting in the config in-world, but the overlay GUI isn't applying the color setting. It should not be affected by the color setting, my pov.

![image](https://user-images.githubusercontent.com/56111366/154275351-1a5f10c8-5198-403b-80aa-794c0b0948b9.png)

![image](https://user-images.githubusercontent.com/56111366/154275442-503c4496-adff-47a3-8a75-4eb46ebbe28b.png)

2022-02-17 09:44 UTC, brachy84 commented
Will fix after this or the other pr is merged

2022-02-19 22:07 UTC, DStrand1 commented
> Had a little test with https://github.com/GregTechCEu/GregTech/pull/645 also merged into my fork. The clipboard follows the UI color setting in the config in-world, but the overlay GUI isn't applying the color setting. It should not be affected by the color setting, my pov.

I will update this in #645 after this merges

2022-02-19 22:08 UTC, Rongmario approved these changes

2022-02-19 22:12 UTC, merged