Localizing miner texts
GregTechCEu/GregTech pull request #672
Opened 2022-02-21 08:59 UTC by ChromaPIE

**What:**
Edited texts displayed in miners' GUI, like `sX: %d` `mZ: %d` and `Chunk Radius: %d` to be localizable. Tested, worked as intended.

**Additional info:**
I don't know if the localization keys are appropriate enough without further editing. Please let me know if not.

2022-02-21 12:03 UTC, Rongmario requested changes
Use: `TextComponentTranslation` instead of wrapping a `I18n.format` in `TextComponentString`. This PR might have to wait after https://github.com/GregTechCEu/GregTech/pull/651 though.

2022-02-21 14:34 UTC, ChromaPIE commented
Ok but for the mining coordinate of Large Miners im still gonna keep what they are to handle those spaces before each lines okay? or are there better ways cuz i know nothing about java coding

2022-02-21 15:53 UTC, ChromaPIE commented
Sorry for the more unwanted commits.

And for that one more localizing work on `MetaTileEntityFusionReactor.java`, I get the reason why it remains harcoded, but I'm also sure that people don't want to see a half width colon in a gui full of full width ones, so yeah I'm giving it a locale key.

2022-02-22 01:36 UTC, ALongStringOfNumbers approved these changes

2022-02-22 10:43 UTC, Rongmario approved these changes

2022-02-23 06:38 UTC, merged