Key map by ItemStackKey
GregTechCEu/GregTech pull request #877
Opened 2022-04-10 01:45 UTC by ALongStringOfNumbers

**What:**
Keys the OreDictionaryItemFilter recently matched map by ItemStackKey instead of ItemStack. This is done because keying by ItemStacks was causing memory issues, due to it not having an equals override.

**Outcome:**
Keys the OreDictionaryItemFilter recently matched map by ItemStackKey instead of ItemStack.

2022-04-10 03:58 UTC, brachy84 approved these changes

2022-04-10 09:08 UTC, Rongmario requested changes
Using `ItemStackKey` obviously is a lot better, but currently it also takes into consideration of the stack's nbt tag, whereas in this situation we only need to hash the Item + its metadata. We might need to use `gregtech.api.util.ItemStackHashStrategy`.

2022-04-11 01:49 UTC, Rongmario requested changes

2022-04-11 01:49 UTC, Rongmario commented on src/main/java/gregtech/common/covers/filter/OreDictionaryItemFilter.java
> +    private final Hash.Strategy<ItemStack> strategy = ItemStackHashStrategy.builder().compareItem(true).compareDamage(true).build();
`private static final` would be nicer

2022-04-11 01:51 UTC, Rongmario approved these changes

2022-04-11 04:28 UTC, merged

2022-04-11 04:29 UTC, brachy84 approved these changes